[IMP] Simplify views and special warning messages
akretion/sale-workflow pull request #20
Opened 2021-02-04 14:37 UTC by kevinkhao

Simplify for easier debugging and reading. The previous implementation caused problems on depending modules like sale_configurator_option_restricted_qty

2021-02-05 12:08 UTC, sebastienbeau requested changes

2021-02-05 12:08 UTC, sebastienbeau commented on sale_restricted_qty/models/sale.py
> +            product_qty = line.product_uom._compute_quantity(
We can do something simplier


```
@api.depend("product_id", "product_uom", "product_uom_qty", "sale_max_qty", "sale_min_qty", "sale_multiple_qty")
def _compute_qty_validity(self):
    for line in self:
            product_qty = line.product_uom._compute_quantity(
                line.product_uom_qty, line.product_id.uom_id)
            
             def compare(qty):
                 return qty and float_compare(
                      product_qty, qty, precision_rounding =  line.product_uom.rounding)

            message = ""
            invalid= False
            if compare(line.sale_min_qty) < 0:
                if line.force_sale_min_qty:
                    message = _("Higher quantity recommended!")
                else:
                    invalid = True
                    message = _("Higher quantity required!")
            if compare(line.sale_max_qty) > 0:
                if self.force_sale_max_qty:
                    message = _("Lower quantity recommended!")
                else:
                    invalid = True
                    message = _("Lower quantity required!")
            if line.sale_multiple_qty and not product_qty % line.sale_multiple_qty:
                    invalid = True
                message += _("\nCorrect multiple of quantity required!")
            line.qty_warning_message = message
            line.qty_invalid = invalid


```

Also store this field

2021-02-05 13:16 UTC, sebastienbeau commented on sale_restricted_qty/views/sale_views.xml
> +               <field name="display_option_ids_danger" invisible="1" />
last thing to fix here:
use danger if "qty_invalid"
use warning if "qty_invadid == False and qty_warning_message"

2021-02-08 07:58 UTC, kevinkhao commented
@sebastienbeau 
note the consideration for storing the quantities from _compute_sale_restricted_qty: if we store these attributes then any update on products or categories will not be taken into account in real time (because the updating function has old info and is not re-triggered)

2021-03-02 20:44 UTC, merged